version: '3'

volumes:
  db_data: {}

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    env_file:
      - .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:10-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"
